//
//  StyleKit.swift
//  Traveller
//
//  Created on 26/09/2016.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

import UIKit



class StyleKit: NSObject {
  
  
  //MARK: - Colors
  
  static let yellow = UIColor(hue: 0.154, saturation: 0.72, brightness: 0.812, alpha: 1)
  static let green = UIColor(hue: 0.456, saturation: 0.422, brightness: 0.455, alpha: 1)
  
  
}
