//
//  StyleKit.swift
//  ObjectiveTea
//
//  Created on 29/09/2016.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

import UIKit



class StyleKit: NSObject {
  
  
  //MARK: - Colors
  
  static let brightMix = UIColor(hue: 0.463, saturation: 0.406, brightness: 1, alpha: 1)
  static let bright = UIColor(hue: 0.463, saturation: 0.487, brightness: 0.972, alpha: 1)
  static let brightBlue = UIColor(hue: 0.582, saturation: 0.693, brightness: 0.963, alpha: 1)
  static let middleBlue = UIColor(hue: 0.585, saturation: 1, brightness: 0.808, alpha: 1)
  static let superBrightBlue = UIColor(hue: 0.554, saturation: 0.689, brightness: 0.94, alpha: 1)
  static let blue = UIColor(hue: 0.614, saturation: 0.771, brightness: 0.935, alpha: 1)
  static let skinColor = UIColor(hue: 0.088, saturation: 0.061, brightness: 0.964, alpha: 1)
  static let blackBlue = UIColor(hue: 0.614, saturation: 0.79, brightness: 0.736, alpha: 1)
  static let blackerBlue = UIColor(hue: 0.614, saturation: 0.732, brightness: 0.486, alpha: 1)
  static let paleMix = UIColor(hue: 0.491, saturation: 0.455, brightness: 0.877, alpha: 1)
  static let lighterMix = UIColor(hue: 0.504, saturation: 0.614, brightness: 0.741, alpha: 1)
  static let lightMix = UIColor(hue: 0.491, saturation: 0.789, brightness: 0.586, alpha: 1)
  static let darkMix = UIColor(hue: 0.504, saturation: 0.773, brightness: 0.418, alpha: 1)
  static let paleRed = UIColor(hue: 0.002, saturation: 0.502, brightness: 0.959, alpha: 1)
  static let lighterRed = UIColor(hue: 0.955, saturation: 0.725, brightness: 0.891, alpha: 1)
  static let lightRed = UIColor(hue: 0.955, saturation: 0.748, brightness: 0.777, alpha: 1)
  static let darkRed = UIColor(hue: 0.955, saturation: 0.756, brightness: 0.694, alpha: 1)
  static let paleOrange = UIColor(hue: 0.114, saturation: 0.447, brightness: 0.935, alpha: 1)
  static let lighterOrange = UIColor(hue: 0.114, saturation: 0.614, brightness: 0.973, alpha: 1)
  static let lightOrange = UIColor(hue: 0.114, saturation: 0.783, brightness: 0.899, alpha: 1)
  static let darkOrange = UIColor(hue: 0.114, saturation: 0.944, brightness: 0.816, alpha: 1)
  static let paleBlue = UIColor(hue: 0.678, saturation: 0.25, brightness: 0.948, alpha: 1)
  static let lighterBlue = UIColor(hue: 0.662, saturation: 0.35, brightness: 0.899, alpha: 1)
  static let lightBlue = UIColor(hue: 0.678, saturation: 0.537, brightness: 0.942, alpha: 1)
  static let darkBlue = UIColor(hue: 0.662, saturation: 0.673, brightness: 0.6, alpha: 1)
  static let paleGreen = UIColor(hue: 0.228, saturation: 0.429, brightness: 0.866, alpha: 1)
  static let lighterGreen = UIColor(hue: 0.227, saturation: 0.628, brightness: 0.78, alpha: 1)
  static let lightGreen = UIColor(hue: 0.227, saturation: 0.768, brightness: 0.608, alpha: 1)
  static let darkGreen = UIColor(hue: 0.421, saturation: 1, brightness: 0.408, alpha: 1)
  
  
}
